### ISSUE TITLE
how to solve this issue??

### ISSUE THREAD

**Issue by newtoreact1** [react-toolbox/react-toolbox-example#39]
ERROR in ./~/react-toolbox/lib/button/theme.scss
Module parse failed: C:\Users\swapnil\Desktop\reactApp\node_modules\react-toolbox\lib\button\theme.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp$4.raise (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:2756:10)
    at Parser.pp$7.readToken (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:2477:17)
    at Parser.pp$7.nextToken (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:2468:15)
    at Parser.parse (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:515:10)
    at Object.parse (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\swapnil\Desktop\reactApp\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\Users\swapnil\Desktop\reactApp\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\Users\swapnil\Desktop\reactApp\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\Users\swapnil\Desktop\reactApp\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
 @ ./~/react-toolbox/lib/button/index.js 26:13-36

ERROR in ./~/react-toolbox/lib/ripple/Ripple.js
Module not found: Error: Cannot resolve module 'immutability-helper' in C:\Users\swapnil\Desktop\reactApp\node_modules\react-toolbox\lib\ripple
 @ ./~/react-toolbox/lib/ripple/Ripple.js 23:26-56

ERROR in ./~/react-toolbox/lib/ripple/theme.scss
Module parse failed: C:\Users\swapnil\Desktop\reactApp\node_modules\react-toolbox\lib\ripple\theme.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp$4.raise (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:2756:10)
    at Parser.pp$7.readToken (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:2477:17)
    at Parser.pp$7.nextToken (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:2468:15)
    at Parser.parse (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:515:10)
    at Object.parse (C:\Users\swapnil\Desktop\reactApp\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\swapnil\Desktop\reactApp\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\Users\swapnil\Desktop\reactApp\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\Users\swapnil\Desktop\reactApp\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\Users\swapnil\Desktop\reactApp\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
 @ ./~/react-toolbox/lib/ripple/index.js 13:13-36
webpack: bundle is now VALID.

**Comment by jcmcneal** [comment]
Looks like you need a proper CSS loader or it's not configured right. Checkout this thread #32 for some configurations.
